# Generated by Django 4.2.26 on 2025-11-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_auto_store_user_retention_period_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='api_key',
            field=models.TextField(),
        ),
    ]
