# Generated by Django 4.2.26 on 2025-11-29 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_integration_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLoadSnapshot',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('value', models.IntegerField(help_text='System load percentage (0-100)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_snapshots', to='api.workspace')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['workspace', '-timestamp'], name='api_systeml_workspa_05ceed_idx')],
            },
        ),
    ]
