# Generated by Django 4.2.26 on 2025-11-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_systemloadsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmemory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this memory is actively included in context'),
        ),
    ]
